name: Rachreiten the book
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  install:
    name: install
    runs-on: macOS-latest
    steps:
      - name: Install Dependencies
        run: yarn install
  build:
    needs: install
    name: build
    runs-on: macOS-latest
    steps:
      - name: Build
        run: yarn build
