name: Rachreiten the book
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master
    paths:
      - "./../.."

jobs:
  build:
    name: deploy
    runs-on: macOS-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
