name: Rachreiten the book
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
        with:
          node-version: 10.x
      - name: Install Dependencies
      run: yarn install
      - name: Build
        run: yarn build
